class Account {
  String name;
  String username;
  String location;
  int age;
  String bio;
  String email;
  String password;
  String gender;
  String job;
  String hobby;
  String skill;
  String favFood;
  String profilePic;

  Account({
    required this.name,
    required this.username,
    required this.location,
    required this.age,
    required this.bio,
    required this.email,
    required this.password,
    required this.gender,
    required this.job,
    required this.hobby,
    required this.skill,
    required this.favFood,
    required this.profilePic,
  });
}

var myAccount = Account(
  name: 'Ronaldo',
  username: 'ronaldo',
  location: 'NTT',
  age: 27,
  bio:
      'Saya Ronaldo yang perkasa, setiap benda berbentuk bola kutendang sekuat tenaga. Namun itu hanya berlangsung selama 7 tahun. Masa-masa itu sangat random sekali, hingga aku tersadar bahwa itu gak guna.',
  email: 'ronaldogantengyahuud@xxx.com',
  password: 'qwerty',
  gender: 'Male',
  job: 'Atlet Bola Bekel',
  skill: 'Tendangan Maut',
  favFood: 'Rujak',
  hobby: 'Menendang apapun yang berbentuk bola',
  profilePic: 'assets/profile_picture/9.jpg',
);

var accountList = [
  Account(
    name: 'Eka Putri',
    username: 'ekaputri',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'Eka Putri lahir dari pasangan ayah Nasrin dan ibu Ika Nuryati pada 16 Juli 1995 di Jambi, namun kedua orang tuanya telah berpisah. Eka merupakan seorang atlet renang Tim Nasional Indonesia dan dia bermain di klub renang Surabaya Bhayangkara Samator. Awal karier Eka di dunia renang ia mulai dari mengikuti turnamen-turnamen di daerahnya, yakni Jambi.',
    email: 'ekaputri@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/1.jpg',
  ),
  Account(
    name: 'ambar',
    username: 'ambarwiwaha',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'ambar21@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/2.jpg',
  ),
  Account(
    name: 'Marya',
    username: 'maryanti',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'marya33@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/3.jpg',
  ),
  Account(
    name: 'Jenifer',
    username: 'jeinfernks',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.',
    email: 'jenifernks@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/4.jpg',
  ),
  Account(
    name: 'Yunisara',
    username: 'yunisaraaa',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'yunisaraaa@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/5.jpg',
  ),
  Account(
    name: 'Muny',
    username: 'munymartin',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'munymartin@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/6.jpg',
  ),
  Account(
    name: 'Indah Ayu',
    username: 'indahayu',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.',
    email: 'indahayu@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/7.jpg',
  ),
  Account(
    name: 'bilaa',
    username: 'bilahita',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'bilahita@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/8.jpg',
  ),
  Account(
    name: 'Munaroh',
    username: 'munaroh',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'munaroh@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/9.jpg',
  ),
  Account(
    name: 'Mala',
    username: 'malaika',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'malaika@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/10.jpg',
  ),
  Account(
    name: 'Tania',
    username: 'tania',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'tania@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/11.jpg',
  ),
  Account(
    name: 'Mona',
    username: 'mona',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.',
    email: 'mona@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/12.jpg',
  ),
  Account(
    name: 'Cici',
    username: 'cici',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'cici@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/13.jpg',
  ),
  Account(
    name: 'Nika',
    username: 'nika',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'nika@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/14.jpg',
  ),
  Account(
    name: 'Amira',
    username: 'amira',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.',
    email: 'amira@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/15.jpg',
  ),
  Account(
    name: 'Putri',
    username: 'putri',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'putri@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/16.jpg',
  ),
  Account(
    name: 'Ema',
    username: 'ema',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'A celebrity is “known for being well-known” (Boorstin, 1961, p. 57), regardless of whether that eminence derives from the entertainment field, medicine, science, politics, religion, sports, or close association with other celebrities. Therefore, “fame” is a psychological concept akin to object-relations theory and is multifaceted in scope. The psychological study of celebrity and fame has generally followed three trends.',
    email: 'ema@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/17.jpg',
  ),
  Account(
    name: 'Ikawa',
    username: 'ikaaawa',
    location: 'Jawa Timur',
    age: 25,
    bio:
        'Topic sentences are similar to mini thesis statements. Like a thesis statement, a topic sentence has a specific main point. Whereas the thesis is the main point of the essay, the topic sentence is the main point of the paragraph. Like the thesis statement, a topic sentence has a unifying function. But a thesis statement or topic sentence alone doesn’t guarantee unity. An essay is unified if all the paragraphs relate to the thesis, whereas a paragraph is unified if all the sentences relate to the topic sentence. Note: Not all paragraphs need topic sentences. In particular, opening and closing paragraphs, which serve different functions from body paragraphs, generally don’t have topic sentences.',
    email: 'ikaaawa@xxx.com',
    password: 'qwerty',
    gender: 'Female',
    job: 'Manager',
    skill: 'apa aja bisa',
    favFood: 'Soto',
    hobby: 'berenang',
    profilePic: 'assets/profile_picture/18.jpg',
  ),
];
